using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using MySql.Data.MySqlClient;

namespace Domain
{
    public class OpenBeerDB
        // Manipulations of the database will use this class
    {
        private string mySqlConnectionString = "SERVER=127.0.0.1; DATABASE=openbeerdb; UID=root; PASSWORD=";
        private MySqlConnection connection;

        public int nbCat { get; private set; } // number of categories of beer in the database
        public int nbSty { get; private set; } // number of styles of beer in the database
        public int nbBeers { get; private set; } // number of beers in the database

        public OpenBeerDB()
        {
            connection = new MySqlConnection(mySqlConnectionString);
            generateFactFile();
        }

        private void generateFactFile()
        {
            List<string> lines = new List<string> { };

            // first comment on top of the file
            lines.Add("%this file is automatically generated from the main program. It musn't be changed in any way, since changes will be erased by the program");

            #region creating lines from the data in the database

            /*
            the names will be automatically generated from the Id of the object in the database before being made into
            a prolog element, since the names in the database often contain unallowed characters in prolog
            */

            #region getting all beers
            List<string[]> beers = AskDataBase("SELECT id FROM beers", new string[] { "id" });
            foreach (string[] beer in beers)
            {
                string prologName = "beer" + beer[0];
                lines.Add("beer(" + prologName + ").");
            }
            #endregion

            #region getting all categories
            List<string[]> categories = AskDataBase("SELECT id FROM categories", new string[] { "id" });
            foreach(string[] category in categories)
            {
                if (int.Parse(category[0]) != -1)
                {
                    string prologName = "category" + category[0];
                    lines.Add("category(" + prologName + ").");
                }
                else
                    lines.Add("category(unknownCategory)."); // We need an unknown category, but the name "category-1" isn't acceptable
            }
            #endregion

            #region getting all styles
            List<string[]> styles = AskDataBase("SELECT id FROM styles", new string[] { "id" });
            foreach (string[] style in styles)
            {
                if (int.Parse(style[0]) != -1)
                {
                    string prologName = "style" + style[0];
                    lines.Add("style(" + prologName + ").");
                }
                else
                    lines.Add("style(unknownStyle)."); // We need an unknown style, but the name "style-1" isn't acceptable
            }
            #endregion

            #region getting all abv (alcohol by volume)
            List<string[]> abvs = AskDataBase("SELECT id,abv FROM beers", new string[] { "id", "abv" });
            foreach (string[] abv in abvs)
            {
                lines.Add("abv(beer"+ abv[0] + ","+abv[1].Replace(',','.')+")."); // decimals should be separated with a dot, not a comma
            }
            #endregion

            #region getting all ibu (internationnal bitterness unit)
            List<string[]> ibus = AskDataBase("SELECT id,ibu FROM beers", new string[] { "id", "ibu" });
            foreach (string[] ibu in ibus)
            {
                lines.Add("ibu(beer" + ibu[0] + "," + ibu[1].Replace(',', '.') + ")."); // decimals should be separated with a dot, not a comma
            }
            #endregion

            #region getting all srm (standard reference method)
            List<string[]> srms = AskDataBase("SELECT id,srm FROM beers", new string[] { "id", "srm" });
            foreach (string[] srm in srms)
            {
                lines.Add("srm(beer" + srm[0] + "," + srm[1].Replace(',', '.') + ")."); // decimals should be separated with a dot, not a comma
            }
            #endregion

            #region getting all beers categories
            List<string[]> beersCat = AskDataBase("SELECT id, cat_id FROM beers", new string[] { "id", "cat_id" });
            foreach (string[] beerCat in beersCat)
            {
                string beerPrologName = "beer" + beerCat[0];
                string catPrologName;
                if (int.Parse(beerCat[1]) != -1)
                    catPrologName = "category" + beerCat[1];
                else
                    catPrologName = "unknownCategory";
                lines.Add("beerCategory(" + beerPrologName + "," + catPrologName + ").");
            }
            #endregion

            #region getting all beers styles
            List<string[]> beersSty = AskDataBase("SELECT id, style_id FROM beers", new string[] { "id", "style_id" });
            foreach (string[] beerSty in beersSty)
            {
                string beerPrologName = "beer" + beerSty[0];
                string styPrologName;
                if (int.Parse(beerSty[1]) != -1)
                    styPrologName = "style" + beerSty[1];
                else
                    styPrologName = "unknownStyle";
                lines.Add("beerStyle(" + beerPrologName + "," + styPrologName + ").");
            }
            #endregion

            #region getting all styles categories
            List<string[]> stylesCat = AskDataBase("SELECT id, cat_id FROM styles", new string[] { "id", "cat_id" });
            foreach (string[] styleCat in stylesCat)
            {
                string stylePrologName;
                if (int.Parse(styleCat[0]) != -1)
                    stylePrologName = "style" + styleCat[0];
                else
                    stylePrologName = "unknownStyle";

                string catPrologName;
                if (int.Parse(styleCat[1]) != -1)
                    catPrologName = "category" + styleCat[1];
                else
                    catPrologName = "unknownCategory";

                lines.Add("styleCategory(" + stylePrologName + "," + catPrologName + ").");
            }
            #endregion

            #region getting all social categories
            List<string[]> socCats = AskDataBase("SELECT id FROM social_categories", new string[] { "id" });
            foreach (string[] socCat in socCats)
            {
                string prologName = "socialCategory" + socCat[0];
                lines.Add("socialCategory(" + prologName + ").");
            }
            #endregion

            #region getting all users
            List<string[]> users = AskDataBase("SELECT id FROM users", new string[] { "id" });
            foreach (string[] user in users)
            {
                string prologName = "user" + user[0];
                lines.Add("user(" + prologName + ").");
            }
            #endregion

            #region getting all users birth years
            List<string[]> bys = AskDataBase("SELECT id, birth_year FROM users", new string[] { "id", "birth_year" });
            foreach (string[] by in bys)
            {
                string prologName = "user" + by[0];
                lines.Add("birthDate(" + prologName + "," + by[1] + ").");
            }
            #endregion

            #region getting all users genders
            List<string[]> genders = AskDataBase("SELECT id, gender FROM users", new string[] { "id", "gender" });
            foreach (string[] gender in genders)
            {
                string prologName = "user" + gender[0];
                string stringGender = (bool.Parse(gender[1])) ? "woman" : "man";
                lines.Add("gender(" + prologName + "," + stringGender + ").");
            }
            #endregion

            #region getting all users social categories
            List<string[]> userSocCats = AskDataBase("SELECT id, social_cat_id FROM users", new string[] { "id", "social_cat_id" });
            foreach (string[] userSocCat in userSocCats)
            {
                string prologName = "user" + userSocCat[0];
                string socCatPlName = "socialCategory" + userSocCat[1];
                lines.Add("userSocialCategory(" + prologName + "," + socCatPlName + ").");
            }
            #endregion

            #region getting all users ratings
            List<string[]> ratings = AskDataBase("SELECT user_id, beer_id, rating FROM ratings", new string[] { "user_id", "beer_id", "rating" });
            foreach (string[] rating in ratings)
            {
                string userPlName = "user" + rating[0];
                string beerPlName = "beer" + rating[1];
                lines.Add("rates(" + userPlName + "," + beerPlName + "," + rating[2].Replace(',','.') + ").");
            }
            #endregion

            #endregion

            using (StreamWriter outputFile = new StreamWriter("..\\..\\..\\PrologEngine\\facts.pl"))
            {
                foreach (string line in lines)
                {
                    outputFile.WriteLine(line);
                }
            }
        }

        public List<string[]> AskDataBase(string query, string[] expectedRows)
        {
            connection.Open();

            List<string[]> results = new List<string[]> { };

            MySqlCommand cmd = connection.CreateCommand();
            cmd.CommandText = query;

            MySqlDataReader reader = cmd.ExecuteReader();

            while (reader.Read())
            {
                string[] thisRow = new string[expectedRows.Length];
                for (int i = 0; i < expectedRows.Length; i++)
                {
                    thisRow[i] = reader.GetString(expectedRows[i]);
                }
                results.Add(thisRow);
            }

            connection.Close();
            return results;
        }

        /*
        // Basic database manipulation :
        public string DBTest()
        {
            this.connection.Open();
            MySqlCommand cmd = connection.CreateCommand();
            cmd.CommandText = "SELECT name,descript FROM beers WHERE id = 1";

            MySqlDataReader reader = cmd.ExecuteReader();
            reader.Read();

            string result = reader.GetString(0);
            result += "\n" + reader.GetString(1);

            connection.Close();

            return result;
        }
        */
    }
}
